# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-05 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('password', models.CharField(max_length=32)),
                ('sign', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=150)),
                ('avatar', models.ImageField(upload_to='avatar/')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
